with open("frontend/app/deal/[id]/memo/page.tsx", "r") as f:
    content = f.read()

import re

injection = """
        {deal.agent_workflow && (
          <div className="bg-slate-50 border p-3 rounded-md mb-6 text-xs text-slate-600 flex flex-wrap gap-4 items-center">
            <span className="font-semibold flex items-center gap-1"><Cpu className="w-3 h-3"/> Generated by Memo Writer Agent</span>
            <span>Mode: {deal.agent_workflow.workflow_mode === 'mock' ? 'Mock Fallback' : 'Live LLM'}</span>
            <span>Sources Reviewed: {deal.agent_workflow.metadata?.sources_reviewed || 0}</span>
            {deal.agent_workflow.final_report?.private_diligence_required && (
              <span className="text-amber-600 font-medium flex items-center gap-1">
                <AlertTriangle className="w-3 h-3"/> {deal.agent_workflow.final_report.private_diligence_required.length} Unknown Metrics
              </span>
            )}
            <span className="text-muted-foreground ml-auto">Generated: {new Date(deal.agent_workflow.metadata?.completed_at || new Date()).toLocaleString()}</span>
          </div>
        )}
"""

if "Generated by Memo Writer Agent" not in content:
    content = content.replace(
        'import { FileText, Target, AlertTriangle, Lightbulb, Scale } from "lucide-react"',
        'import { FileText, Target, AlertTriangle, Lightbulb, Scale, Cpu } from "lucide-react"'
    )
    content = content.replace(
        '      <Card className="max-w-4xl mx-auto shadow-md">\n        <CardContent className="p-8 space-y-8">',
        '      <Card className="max-w-4xl mx-auto shadow-md">\n        <CardContent className="p-8 space-y-8">' + injection
    )
    with open("frontend/app/deal/[id]/memo/page.tsx", "w") as f:
        f.write(content)
