import { api } from "@/lib/api"
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Mail, Copy, Send, Edit } from "lucide-react"

export default async function FounderEmailPage(props: { params: Promise<{ id: string }> }) {
  const params = await props.params;
  const deal = await api.getDeal(params.id)
  
  let emailData: any = null
  try {
    const res = await fetch(`${"http://127.0.0.1:8000"}/deals/${params.id}/founder-email`)
    if (res.ok) emailData = await res.json()
  } catch (e) {
    console.error(e)
  }

  if (!emailData) {
    return (
      <div className="flex-1 p-8 pt-6 space-y-6 flex items-center justify-center min-h-[50vh]">
        <div className="text-center">
          <h1 className="text-xl font-bold tracking-tight text-foreground">Drafting Founder Email...</h1>
          <p className="text-sm text-muted-foreground mt-2 animate-pulse">Analyzing diligence gaps to generate questions</p>
        </div>
      </div>
    )
  }

  return (
    <div className="flex-1 p-8 pt-6 space-y-8 min-h-screen bg-muted/10 pb-20">
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-3xl font-bold tracking-tight text-foreground">Draft Founder Email</h1>
            <Badge variant="secondary" className="font-mono">{deal.startup_name}</Badge>
          </div>
          <p className="text-muted-foreground mt-1">AI-generated follow-up based on identified diligence gaps</p>
        </div>
      </div>

      <Card className="max-w-3xl border shadow-sm">
        <CardHeader className="bg-muted/30 border-b pb-4">
          <div className="flex justify-between items-center">
            <CardTitle className="text-sm font-medium text-muted-foreground uppercase tracking-wider flex items-center gap-2">
              <Mail className="w-4 h-4" /> Message Draft
            </CardTitle>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" className="h-8">
                <Edit className="w-3 h-3 mr-2" />
                Edit
              </Button>
              <Button variant="outline" size="sm" className="h-8">
                <Copy className="w-3 h-3 mr-2" />
                Copy
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <div className="border-b px-6 py-3 flex items-center gap-4 text-sm">
            <span className="font-semibold text-muted-foreground w-16">To:</span>
            <span className="text-foreground">founders@{deal.startup_name.toLowerCase().replace(/ /g, "")}.com</span>
          </div>
          <div className="border-b px-6 py-3 flex items-center gap-4 text-sm">
            <span className="font-semibold text-muted-foreground w-16">Subject:</span>
            <span className="text-foreground font-medium">{emailData.subject}</span>
          </div>
          <div className="px-6 py-6 text-sm text-foreground whitespace-pre-wrap font-sans leading-relaxed">
            {emailData.body}
          </div>
        </CardContent>
        <CardFooter className="bg-muted/10 border-t px-6 py-4 flex justify-between">
          <p className="text-xs text-muted-foreground">Draft generated by Apex Capital Diligence Engine</p>
          <Button size="sm">
            <Send className="w-3 h-3 mr-2" />
            Send via Superhuman
          </Button>
        </CardFooter>
      </Card>
      
    </div>
  )
}
