"""001_initial

Revision ID: 06d3bbdc5c74
Revises: 
Create Date: 2026-06-09 16:03:31.449347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d3bbdc5c74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('startup_name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('sub_sector', sa.String(), nullable=True),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('business_model', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('founder_background', sa.Text(), nullable=True),
    sa.Column('market_size', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('mrr', sa.Float(), nullable=True),
    sa.Column('arr', sa.Float(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('customers', sa.Integer(), nullable=True),
    sa.Column('retention_rate', sa.Float(), nullable=True),
    sa.Column('churn_rate', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('cac', sa.Float(), nullable=True),
    sa.Column('ltv', sa.Float(), nullable=True),
    sa.Column('funding_raised', sa.Float(), nullable=True),
    sa.Column('valuation', sa.Float(), nullable=True),
    sa.Column('competitors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_created_at'), 'deals', ['created_at'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_startup_name'), 'deals', ['startup_name'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_index(op.f('ix_deals_workspace_id'), 'deals', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_id'), 'workspace_members', ['id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('full_analysis_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_deal_id'), 'analyses', ['deal_id'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_analyses_workspace_id'), 'analyses', ['workspace_id'], unique=False)
    op.create_table('conversation_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('founder_response_quality_score', sa.Integer(), nullable=True),
    sa.Column('clarity_score', sa.Integer(), nullable=True),
    sa.Column('responsiveness_score', sa.Integer(), nullable=True),
    sa.Column('credibility_score', sa.Integer(), nullable=True),
    sa.Column('evidence_provided_score', sa.Integer(), nullable=True),
    sa.Column('contradiction_risk_score', sa.Integer(), nullable=True),
    sa.Column('overall_conversation_score', sa.Integer(), nullable=True),
    sa.Column('scorecard_json', sa.JSON(), nullable=True),
    sa.Column('founder_analysis_json', sa.JSON(), nullable=True),
    sa.Column('investor_questions_json', sa.JSON(), nullable=True),
    sa.Column('positive_signals_json', sa.JSON(), nullable=True),
    sa.Column('negative_signals_json', sa.JSON(), nullable=True),
    sa.Column('contradictions_json', sa.JSON(), nullable=True),
    sa.Column('evidence_extracted_json', sa.JSON(), nullable=True),
    sa.Column('open_followups_json', sa.JSON(), nullable=True),
    sa.Column('decision_impact_json', sa.JSON(), nullable=True),
    sa.Column('recommendation_adjustment', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_intelligence_created_at'), 'conversation_intelligence', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_intelligence_deal_id'), 'conversation_intelligence', ['deal_id'], unique=True)
    op.create_index(op.f('ix_conversation_intelligence_id'), 'conversation_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_intelligence_workspace_id'), 'conversation_intelligence', ['workspace_id'], unique=False)
    op.create_table('conversation_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('conversation_type', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('participants_json', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_messages_json', sa.JSON(), nullable=True),
    sa.Column('round_score', sa.Integer(), nullable=True),
    sa.Column('key_signal', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_rounds_created_at'), 'conversation_rounds', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_rounds_deal_id'), 'conversation_rounds', ['deal_id'], unique=False)
    op.create_index(op.f('ix_conversation_rounds_id'), 'conversation_rounds', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_rounds_workspace_id'), 'conversation_rounds', ['workspace_id'], unique=False)
    op.create_table('deck_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('deck_name', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_sections_json', sa.Text(), nullable=True),
    sa.Column('key_claims_json', sa.Text(), nullable=True),
    sa.Column('traction_json', sa.Text(), nullable=True),
    sa.Column('financials_json', sa.Text(), nullable=True),
    sa.Column('risks_json', sa.Text(), nullable=True),
    sa.Column('missing_sections_json', sa.Text(), nullable=True),
    sa.Column('deck_quality_json', sa.Text(), nullable=True),
    sa.Column('readiness_breakdown_json', sa.Text(), nullable=True),
    sa.Column('recommended_follow_up_questions_json', sa.Text(), nullable=True),
    sa.Column('deck_summary', sa.Text(), nullable=True),
    sa.Column('deck_quality_score', sa.Integer(), nullable=True),
    sa.Column('investor_readiness_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_analyses_deal_id'), 'deck_analyses', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deck_analyses_id'), 'deck_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_deck_analyses_workspace_id'), 'deck_analyses', ['workspace_id'], unique=False)
    op.create_table('diligence_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('ic_readiness_score', sa.Integer(), nullable=True),
    sa.Column('diligence_status', sa.String(), nullable=True),
    sa.Column('final_diligence_verdict', sa.String(), nullable=True),
    sa.Column('priority_tasks_json', sa.Text(), nullable=True),
    sa.Column('claim_verifications_json', sa.Text(), nullable=True),
    sa.Column('founder_followups_json', sa.Text(), nullable=True),
    sa.Column('customer_reference_questions_json', sa.Text(), nullable=True),
    sa.Column('data_room_requests_json', sa.Text(), nullable=True),
    sa.Column('risk_resolution_plan_json', sa.Text(), nullable=True),
    sa.Column('evidence_items_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diligence_plans_deal_id'), 'diligence_plans', ['deal_id'], unique=False)
    op.create_index(op.f('ix_diligence_plans_id'), 'diligence_plans', ['id'], unique=False)
    op.create_index(op.f('ix_diligence_plans_workspace_id'), 'diligence_plans', ['workspace_id'], unique=False)
    op.create_table('fund_fit_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('fund_size', sa.Integer(), nullable=True),
    sa.Column('initial_check_size', sa.Integer(), nullable=True),
    sa.Column('target_ownership', sa.Float(), nullable=True),
    sa.Column('required_exit_value_for_1x_fund', sa.Integer(), nullable=True),
    sa.Column('fund_return_potential', sa.String(), nullable=True),
    sa.Column('thesis_fit_score', sa.Integer(), nullable=True),
    sa.Column('portfolio_concentration_risk', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('key_constraints_json', sa.Text(), nullable=True),
    sa.Column('thesis_fit_json', sa.Text(), nullable=True),
    sa.Column('ownership_scenarios_json', sa.Text(), nullable=True),
    sa.Column('reserve_strategy_json', sa.Text(), nullable=True),
    sa.Column('power_law_simulation_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_fit_assessments_deal_id'), 'fund_fit_assessments', ['deal_id'], unique=False)
    op.create_index(op.f('ix_fund_fit_assessments_id'), 'fund_fit_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_fund_fit_assessments_recommendation'), 'fund_fit_assessments', ['recommendation'], unique=False)
    op.create_index(op.f('ix_fund_fit_assessments_workspace_id'), 'fund_fit_assessments', ['workspace_id'], unique=False)
    op.create_table('ic_decision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('partner_concerns', sa.Text(), nullable=True),
    sa.Column('next_step', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ic_decision_logs_deal_id'), 'ic_decision_logs', ['deal_id'], unique=False)
    op.create_index(op.f('ix_ic_decision_logs_decision'), 'ic_decision_logs', ['decision'], unique=False)
    op.create_index(op.f('ix_ic_decision_logs_id'), 'ic_decision_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ic_decision_logs_workspace_id'), 'ic_decision_logs', ['workspace_id'], unique=False)
    op.create_table('research_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('market_research_json', sa.Text(), nullable=True),
    sa.Column('competitor_research_json', sa.Text(), nullable=True),
    sa.Column('customer_personas_json', sa.Text(), nullable=True),
    sa.Column('pricing_research_json', sa.Text(), nullable=True),
    sa.Column('gtm_research_json', sa.Text(), nullable=True),
    sa.Column('tam_sam_som_json', sa.Text(), nullable=True),
    sa.Column('evidence_grade_json', sa.Text(), nullable=True),
    sa.Column('source_registry_json', sa.Text(), nullable=True),
    sa.Column('research_gaps_json', sa.Text(), nullable=True),
    sa.Column('source_confidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_briefs_deal_id'), 'research_briefs', ['deal_id'], unique=False)
    op.create_index(op.f('ix_research_briefs_id'), 'research_briefs', ['id'], unique=False)
    op.create_index(op.f('ix_research_briefs_workspace_id'), 'research_briefs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_briefs_workspace_id'), table_name='research_briefs')
    op.drop_index(op.f('ix_research_briefs_id'), table_name='research_briefs')
    op.drop_index(op.f('ix_research_briefs_deal_id'), table_name='research_briefs')
    op.drop_table('research_briefs')
    op.drop_index(op.f('ix_ic_decision_logs_workspace_id'), table_name='ic_decision_logs')
    op.drop_index(op.f('ix_ic_decision_logs_id'), table_name='ic_decision_logs')
    op.drop_index(op.f('ix_ic_decision_logs_decision'), table_name='ic_decision_logs')
    op.drop_index(op.f('ix_ic_decision_logs_deal_id'), table_name='ic_decision_logs')
    op.drop_table('ic_decision_logs')
    op.drop_index(op.f('ix_fund_fit_assessments_workspace_id'), table_name='fund_fit_assessments')
    op.drop_index(op.f('ix_fund_fit_assessments_recommendation'), table_name='fund_fit_assessments')
    op.drop_index(op.f('ix_fund_fit_assessments_id'), table_name='fund_fit_assessments')
    op.drop_index(op.f('ix_fund_fit_assessments_deal_id'), table_name='fund_fit_assessments')
    op.drop_table('fund_fit_assessments')
    op.drop_index(op.f('ix_diligence_plans_workspace_id'), table_name='diligence_plans')
    op.drop_index(op.f('ix_diligence_plans_id'), table_name='diligence_plans')
    op.drop_index(op.f('ix_diligence_plans_deal_id'), table_name='diligence_plans')
    op.drop_table('diligence_plans')
    op.drop_index(op.f('ix_deck_analyses_workspace_id'), table_name='deck_analyses')
    op.drop_index(op.f('ix_deck_analyses_id'), table_name='deck_analyses')
    op.drop_index(op.f('ix_deck_analyses_deal_id'), table_name='deck_analyses')
    op.drop_table('deck_analyses')
    op.drop_index(op.f('ix_conversation_rounds_workspace_id'), table_name='conversation_rounds')
    op.drop_index(op.f('ix_conversation_rounds_id'), table_name='conversation_rounds')
    op.drop_index(op.f('ix_conversation_rounds_deal_id'), table_name='conversation_rounds')
    op.drop_index(op.f('ix_conversation_rounds_created_at'), table_name='conversation_rounds')
    op.drop_table('conversation_rounds')
    op.drop_index(op.f('ix_conversation_intelligence_workspace_id'), table_name='conversation_intelligence')
    op.drop_index(op.f('ix_conversation_intelligence_id'), table_name='conversation_intelligence')
    op.drop_index(op.f('ix_conversation_intelligence_deal_id'), table_name='conversation_intelligence')
    op.drop_index(op.f('ix_conversation_intelligence_created_at'), table_name='conversation_intelligence')
    op.drop_table('conversation_intelligence')
    op.drop_index(op.f('ix_analyses_workspace_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_deal_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_workspace_members_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_deals_workspace_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_startup_name'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_created_at'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
