"""apex_4_v2

Revision ID: 63de8db1c619
Revises: e3f438b2c7ca
Create Date: 2026-07-12 19:02:11.723826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63de8db1c619'
down_revision: Union[str, Sequence[str], None] = 'e3f438b2c7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_events_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_event_type'), ['event_type'], unique=False)

    op.create_table('review_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('deck_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage_json', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_runs_decision_id'), ['decision_id'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('linked_assumption_id', sa.Integer(), nullable=True),
    sa.Column('linked_conflict_id', sa.Integer(), nullable=True),
    sa.Column('linked_claim_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_assumption_id'], ['assumptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_claim_id'], ['claims.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_conflict_id'], ['evidence_conflicts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_items_decision_id'), ['decision_id'], unique=False)

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deck_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('previous_version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_stale', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_evidence_previous_version_id', 'evidence', ['previous_version_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evidence_previous_version_id', type_='foreignkey')
        batch_op.drop_column('is_stale')
        batch_op.drop_column('previous_version_id')
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('deck_version')
        batch_op.drop_column('version')
        batch_op.drop_column('last_modified_at')

    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_items_decision_id'))

    op.drop_table('action_items')
    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_runs_decision_id'))

    op.drop_table('review_runs')
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_domain_events_decision_id'))

    op.drop_table('domain_events')
    # ### end Alembic commands ###
