"""Phase 5 and 6 Updates

Revision ID: 7397de62b953
Revises: d806a11fb8be
Create Date: 2026-07-03 19:42:02.571112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7397de62b953'
down_revision: Union[str, Sequence[str], None] = 'd806a11fb8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_run_id', sa.String(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('structured_output_validity', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_telemetry_decision_id'), 'model_telemetry', ['decision_id'], unique=False)
    op.create_index(op.f('ix_model_telemetry_evaluation_run_id'), 'model_telemetry', ['evaluation_run_id'], unique=False)
    op.create_table('assertions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assertion_id', sa.String(), nullable=True),
    sa.Column('evaluation_run_id', sa.String(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_agent', sa.String(), nullable=True),
    sa.Column('assertion_text', sa.Text(), nullable=True),
    sa.Column('assertion_type', sa.String(), nullable=True),
    sa.Column('cited_claim_ids_json', sa.Text(), nullable=True),
    sa.Column('cited_assumption_ids_json', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('validation_method', sa.String(), nullable=True),
    sa.Column('validation_rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assertions_assertion_id'), 'assertions', ['assertion_id'], unique=False)
    op.create_index(op.f('ix_assertions_decision_id'), 'assertions', ['decision_id'], unique=False)
    op.create_index(op.f('ix_assertions_evaluation_run_id'), 'assertions', ['evaluation_run_id'], unique=False)
    op.create_table('challenge_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_run_id', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('challenge_question', sa.Text(), nullable=True),
    sa.Column('why_material', sa.Text(), nullable=True),
    sa.Column('supporting_evidence_ids_json', sa.Text(), nullable=True),
    sa.Column('contradicting_evidence_ids_json', sa.Text(), nullable=True),
    sa.Column('missing_information', sa.Text(), nullable=True),
    sa.Column('challenge_mode', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('challenge_findings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_tasks_decision_id'), 'challenge_tasks', ['decision_id'], unique=False)
    op.create_index(op.f('ix_challenge_tasks_evaluation_run_id'), 'challenge_tasks', ['evaluation_run_id'], unique=False)
    op.create_table('escalation_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_run_id', sa.String(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('source_claim_ids_json', sa.Text(), nullable=True),
    sa.Column('source_assumption_ids_json', sa.Text(), nullable=True),
    sa.Column('source_conflict_ids_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recommended_challenge_type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_signals_decision_id'), 'escalation_signals', ['decision_id'], unique=False)
    op.create_index(op.f('ix_escalation_signals_evaluation_run_id'), 'escalation_signals', ['evaluation_run_id'], unique=False)
    op.create_index(op.f('ix_escalation_signals_signal_type'), 'escalation_signals', ['signal_type'], unique=False)
    op.create_table('challenge_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('challenge_task_id', sa.Integer(), nullable=True),
    sa.Column('position_changed', sa.Boolean(), nullable=True),
    sa.Column('position_before', sa.String(), nullable=True),
    sa.Column('position_after', sa.String(), nullable=True),
    sa.Column('confidence_before', sa.Integer(), nullable=True),
    sa.Column('confidence_after', sa.Integer(), nullable=True),
    sa.Column('new_evidence_relationships_json', sa.Text(), nullable=True),
    sa.Column('unresolved_questions', sa.Text(), nullable=True),
    sa.Column('conditions_for_reversal', sa.Text(), nullable=True),
    sa.Column('recommendation_impact', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_task_id'], ['challenge_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_findings_challenge_task_id'), 'challenge_findings', ['challenge_task_id'], unique=False)
    op.create_index(op.f('ix_challenge_findings_decision_id'), 'challenge_findings', ['decision_id'], unique=False)
    op.create_table('decision_integrity_envelopes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('reasoning_run_id', sa.Integer(), nullable=True),
    sa.Column('hard_conflicts_json', sa.Text(), nullable=True),
    sa.Column('critical_assumptions_json', sa.Text(), nullable=True),
    sa.Column('unresolved_high_severity_signals_json', sa.Text(), nullable=True),
    sa.Column('mandatory_human_review', sa.Boolean(), nullable=True),
    sa.Column('blocking_conditions_json', sa.Text(), nullable=True),
    sa.Column('required_next_actions_json', sa.Text(), nullable=True),
    sa.Column('integrity_status', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('formula_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reasoning_run_id'], ['reasoning_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_integrity_envelopes_decision_id'), 'decision_integrity_envelopes', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_integrity_envelopes_reasoning_run_id'), 'decision_integrity_envelopes', ['reasoning_run_id'], unique=False)
    op.create_index(op.f('ix_decision_integrity_envelopes_recommendation_id'), 'decision_integrity_envelopes', ['recommendation_id'], unique=False)
    op.create_table('evidence_conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relationship_id', sa.String(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('claim_a_id', sa.Integer(), nullable=True),
    sa.Column('claim_b_id', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('resolution_status', sa.String(), nullable=True),
    sa.Column('resolution_rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_a_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_b_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_conflicts_decision_id'), 'evidence_conflicts', ['decision_id'], unique=False)
    op.create_index(op.f('ix_evidence_conflicts_relationship_id'), 'evidence_conflicts', ['relationship_id'], unique=False)
    op.add_column('reasoning_runs', sa.Column('experiment_batch_id', sa.String(), nullable=True))
    op.add_column('reasoning_runs', sa.Column('grading_status', sa.String(), nullable=True))
    op.add_column('reasoning_runs', sa.Column('grader_failure_reason', sa.String(), nullable=True))
    op.add_column('reasoning_runs', sa.Column('intermediate_state_json', sa.Text(), nullable=True))
    op.create_index(op.f('ix_reasoning_runs_experiment_batch_id'), 'reasoning_runs', ['experiment_batch_id'], unique=False)
    op.add_column('recommendations', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'status')
    op.drop_index(op.f('ix_reasoning_runs_experiment_batch_id'), table_name='reasoning_runs')
    op.drop_column('reasoning_runs', 'intermediate_state_json')
    op.drop_column('reasoning_runs', 'grader_failure_reason')
    op.drop_column('reasoning_runs', 'grading_status')
    op.drop_column('reasoning_runs', 'experiment_batch_id')
    op.drop_index(op.f('ix_evidence_conflicts_relationship_id'), table_name='evidence_conflicts')
    op.drop_index(op.f('ix_evidence_conflicts_decision_id'), table_name='evidence_conflicts')
    op.drop_table('evidence_conflicts')
    op.drop_index(op.f('ix_decision_integrity_envelopes_recommendation_id'), table_name='decision_integrity_envelopes')
    op.drop_index(op.f('ix_decision_integrity_envelopes_reasoning_run_id'), table_name='decision_integrity_envelopes')
    op.drop_index(op.f('ix_decision_integrity_envelopes_decision_id'), table_name='decision_integrity_envelopes')
    op.drop_table('decision_integrity_envelopes')
    op.drop_index(op.f('ix_challenge_findings_decision_id'), table_name='challenge_findings')
    op.drop_index(op.f('ix_challenge_findings_challenge_task_id'), table_name='challenge_findings')
    op.drop_table('challenge_findings')
    op.drop_index(op.f('ix_escalation_signals_signal_type'), table_name='escalation_signals')
    op.drop_index(op.f('ix_escalation_signals_evaluation_run_id'), table_name='escalation_signals')
    op.drop_index(op.f('ix_escalation_signals_decision_id'), table_name='escalation_signals')
    op.drop_table('escalation_signals')
    op.drop_index(op.f('ix_challenge_tasks_evaluation_run_id'), table_name='challenge_tasks')
    op.drop_index(op.f('ix_challenge_tasks_decision_id'), table_name='challenge_tasks')
    op.drop_table('challenge_tasks')
    op.drop_index(op.f('ix_assertions_evaluation_run_id'), table_name='assertions')
    op.drop_index(op.f('ix_assertions_decision_id'), table_name='assertions')
    op.drop_index(op.f('ix_assertions_assertion_id'), table_name='assertions')
    op.drop_table('assertions')
    op.drop_index(op.f('ix_model_telemetry_evaluation_run_id'), table_name='model_telemetry')
    op.drop_index(op.f('ix_model_telemetry_decision_id'), table_name='model_telemetry')
    op.drop_table('model_telemetry')
    # ### end Alembic commands ###
