"""Init V4 Schema

Revision ID: 79c1b9ef2ad2
Revises: 
Create Date: 2026-06-30 15:16:11.356270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '79c1b9ef2ad2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missing_info_items_deal_id'), table_name='missing_info_items')
    op.drop_index(op.f('ix_missing_info_items_id'), table_name='missing_info_items')
    op.drop_table('missing_info_items')
    op.drop_index(op.f('ix_analyses_deal_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_workspace_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_conversation_intelligence_created_at'), table_name='conversation_intelligence')
    op.drop_index(op.f('ix_conversation_intelligence_deal_id'), table_name='conversation_intelligence')
    op.drop_index(op.f('ix_conversation_intelligence_id'), table_name='conversation_intelligence')
    op.drop_index(op.f('ix_conversation_intelligence_workspace_id'), table_name='conversation_intelligence')
    op.drop_table('conversation_intelligence')
    op.drop_index(op.f('ix_ic_decision_logs_deal_id'), table_name='ic_decision_logs')
    op.drop_index(op.f('ix_ic_decision_logs_decision'), table_name='ic_decision_logs')
    op.drop_index(op.f('ix_ic_decision_logs_id'), table_name='ic_decision_logs')
    op.drop_index(op.f('ix_ic_decision_logs_workspace_id'), table_name='ic_decision_logs')
    op.drop_table('ic_decision_logs')
    op.drop_index(op.f('ix_conversation_rounds_created_at'), table_name='conversation_rounds')
    op.drop_index(op.f('ix_conversation_rounds_deal_id'), table_name='conversation_rounds')
    op.drop_index(op.f('ix_conversation_rounds_id'), table_name='conversation_rounds')
    op.drop_index(op.f('ix_conversation_rounds_workspace_id'), table_name='conversation_rounds')
    op.drop_table('conversation_rounds')
    op.drop_index(op.f('ix_workspace_members_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_investment_theses_deal_id'), table_name='investment_theses')
    op.drop_index(op.f('ix_investment_theses_id'), table_name='investment_theses')
    op.drop_table('investment_theses')
    op.drop_index(op.f('ix_demo_seed_status_id'), table_name='demo_seed_status')
    op.drop_table('demo_seed_status')
    op.drop_index(op.f('ix_deal_data_room_reports_id'), table_name='deal_data_room_reports')
    op.drop_table('deal_data_room_reports')
    op.drop_index(op.f('ix_agent_workflow_runs_deal_id'), table_name='agent_workflow_runs')
    op.drop_index(op.f('ix_agent_workflow_runs_run_id'), table_name='agent_workflow_runs')
    op.drop_table('agent_workflow_runs')
    op.drop_index(op.f('ix_decision_audit_logs_deal_id'), table_name='decision_audit_logs')
    op.drop_index(op.f('ix_decision_audit_logs_id'), table_name='decision_audit_logs')
    op.drop_table('decision_audit_logs')
    op.drop_index(op.f('ix_diligence_plans_deal_id'), table_name='diligence_plans')
    op.drop_index(op.f('ix_diligence_plans_id'), table_name='diligence_plans')
    op.drop_index(op.f('ix_diligence_plans_workspace_id'), table_name='diligence_plans')
    op.drop_table('diligence_plans')
    op.drop_index(op.f('ix_web_sources_id'), table_name='web_sources')
    op.drop_index(op.f('ix_web_sources_research_id'), table_name='web_sources')
    op.drop_table('web_sources')
    op.drop_index(op.f('ix_deal_documents_id'), table_name='deal_documents')
    op.drop_table('deal_documents')
    op.drop_index(op.f('ix_platform_signals_deal_id'), table_name='platform_signals')
    op.drop_index(op.f('ix_platform_signals_platform'), table_name='platform_signals')
    op.drop_index(op.f('ix_platform_signals_run_id'), table_name='platform_signals')
    op.drop_index(op.f('ix_platform_signals_signal_id'), table_name='platform_signals')
    op.drop_table('platform_signals')
    op.drop_index(op.f('ix_deal_war_rooms_deal_id'), table_name='deal_war_rooms')
    op.drop_index(op.f('ix_deal_war_rooms_id'), table_name='deal_war_rooms')
    op.drop_index(op.f('ix_deal_war_rooms_workspace_id'), table_name='deal_war_rooms')
    op.drop_table('deal_war_rooms')
    op.drop_index(op.f('ix_deck_analyses_deal_id'), table_name='deck_analyses')
    op.drop_index(op.f('ix_deck_analyses_id'), table_name='deck_analyses')
    op.drop_index(op.f('ix_deck_analyses_workspace_id'), table_name='deck_analyses')
    op.drop_table('deck_analyses')
    op.drop_index(op.f('ix_uploaded_files_deal_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_workspace_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_agent_traces_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_run_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index(op.f('ix_deal_data_room_documents_document_id'), table_name='deal_data_room_documents')
    op.drop_index(op.f('ix_deal_data_room_documents_id'), table_name='deal_data_room_documents')
    op.drop_table('deal_data_room_documents')
    op.drop_index(op.f('ix_diligence_runs_deal_id'), table_name='diligence_runs')
    op.drop_index(op.f('ix_diligence_runs_id'), table_name='diligence_runs')
    op.drop_table('diligence_runs')
    op.drop_index(op.f('ix_diligence_run_steps_id'), table_name='diligence_run_steps')
    op.drop_index(op.f('ix_diligence_run_steps_run_id'), table_name='diligence_run_steps')
    op.drop_table('diligence_run_steps')
    op.drop_index(op.f('ix_web_research_briefs_deal_id'), table_name='web_research_briefs')
    op.drop_index(op.f('ix_web_research_briefs_id'), table_name='web_research_briefs')
    op.drop_index(op.f('ix_web_research_briefs_workspace_id'), table_name='web_research_briefs')
    op.drop_table('web_research_briefs')
    op.drop_index(op.f('ix_platform_diligence_runs_deal_id'), table_name='platform_diligence_runs')
    op.drop_index(op.f('ix_platform_diligence_runs_id'), table_name='platform_diligence_runs')
    op.drop_table('platform_diligence_runs')
    op.drop_index(op.f('ix_assumptions_deal_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_trust_audits_deal_id'), table_name='trust_audits')
    op.drop_index(op.f('ix_trust_audits_id'), table_name='trust_audits')
    op.drop_table('trust_audits')
    op.drop_index(op.f('ix_decision_outputs_deal_id'), table_name='decision_outputs')
    op.drop_index(op.f('ix_decision_outputs_id'), table_name='decision_outputs')
    op.drop_table('decision_outputs')
    op.drop_index(op.f('ix_operation_tasks_deal_id'), table_name='operation_tasks')
    op.drop_index(op.f('ix_operation_tasks_id'), table_name='operation_tasks')
    op.drop_table('operation_tasks')
    op.drop_index(op.f('ix_evidence_items_deal_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_red_flags_deal_id'), table_name='red_flags')
    op.drop_index(op.f('ix_red_flags_id'), table_name='red_flags')
    op.drop_table('red_flags')
    op.drop_index(op.f('ix_fund_fit_assessments_deal_id'), table_name='fund_fit_assessments')
    op.drop_index(op.f('ix_fund_fit_assessments_id'), table_name='fund_fit_assessments')
    op.drop_index(op.f('ix_fund_fit_assessments_recommendation'), table_name='fund_fit_assessments')
    op.drop_index(op.f('ix_fund_fit_assessments_workspace_id'), table_name='fund_fit_assessments')
    op.drop_table('fund_fit_assessments')
    op.drop_index(op.f('ix_ic_packets_deal_id'), table_name='ic_packets')
    op.drop_index(op.f('ix_ic_packets_id'), table_name='ic_packets')
    op.drop_table('ic_packets')
    op.drop_index(op.f('ix_platform_sources_id'), table_name='platform_sources')
    op.drop_index(op.f('ix_platform_sources_name'), table_name='platform_sources')
    op.drop_table('platform_sources')
    op.drop_index(op.f('ix_research_briefs_deal_id'), table_name='research_briefs')
    op.drop_index(op.f('ix_research_briefs_id'), table_name='research_briefs')
    op.drop_index(op.f('ix_research_briefs_workspace_id'), table_name='research_briefs')
    op.drop_table('research_briefs')
    op.drop_index(op.f('ix_deal_comments_deal_id'), table_name='deal_comments')
    op.drop_index(op.f('ix_deal_comments_id'), table_name='deal_comments')
    op.drop_table('deal_comments')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_deal_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'workspace_id')
    op.create_index(op.f('ix_deal_assignments_user_id'), 'deal_assignments', ['user_id'], unique=False)
    op.drop_column('deal_assignments', 'created_at')
    op.add_column('deals', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('funding_asking', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_deals_created_at'), table_name='deals')
    op.drop_index(op.f('ix_deals_startup_name'), table_name='deals')
    op.drop_index(op.f('ix_deals_workspace_id'), table_name='deals')
    op.create_index(op.f('ix_deals_company_id'), 'deals', ['company_id'], unique=False)
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('deals', 'funding_raised')
    op.drop_column('deals', 'business_model')
    op.drop_column('deals', 'traction_summary')
    op.drop_column('deals', 'is_demo')
    op.drop_column('deals', 'is_public_benchmark')
    op.drop_column('deals', 'founder_name')
    op.drop_column('deals', 'mrr')
    op.drop_column('deals', 'deal_type')
    op.drop_column('deals', 'sector')
    op.drop_column('deals', 'workspace_id')
    op.drop_column('deals', 'growth_rate')
    op.drop_column('deals', 'evidence_confidence')
    op.drop_column('deals', 'competitors')
    op.drop_column('deals', 'public_profile_json')
    op.drop_column('deals', 'founder_background')
    op.drop_column('deals', 'why_interesting')
    op.drop_column('deals', 'notes')
    op.drop_column('deals', 'tags')
    op.drop_column('deals', 'active_playbook_id')
    op.drop_column('deals', 'website')
    op.drop_column('deals', 'gross_margin')
    op.drop_column('deals', 'round_size')
    op.drop_column('deals', 'users')
    op.drop_column('deals', 'description')
    op.drop_column('deals', 'fundraising_status')
    op.drop_column('deals', 'revenue')
    op.drop_column('deals', 'ltv')
    op.drop_column('deals', 'revenue_summary')
    op.drop_column('deals', 'churn_rate')
    op.drop_column('deals', 'ic_readiness')
    op.drop_column('deals', 'is_archived')
    op.drop_column('deals', 'founder_email')
    op.drop_column('deals', 'startup_name')
    op.drop_column('deals', 'arr')
    op.drop_column('deals', 'customer_summary')
    op.drop_column('deals', 'source_type')
    op.drop_column('deals', 'sub_sector')
    op.drop_column('deals', 'customers')
    op.drop_column('deals', 'retention_rate')
    op.drop_column('deals', 'recommendation')
    op.drop_column('deals', 'trust_score')
    op.drop_column('deals', 'cac')
    op.drop_column('deals', 'geography')
    op.drop_column('deals', 'market_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('market_size', sa.FLOAT(), nullable=True))
    op.add_column('deals', sa.Column('geography', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('cac', sa.FLOAT(), nullable=True))
    op.add_column('deals', sa.Column('trust_score', sa.INTEGER(), nullable=True))
    op.add_column('deals', sa.Column('recommendation', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('retention_rate', sa.FLOAT(), nullable=True))
    op.add_column('deals', sa.Column('customers', sa.INTEGER(), nullable=True))
    op.add_column('deals', sa.Column('sub_sector', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('source_type', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('customer_summary', sa.TEXT(), nullable=True))
    op.add_column('deals', sa.Column('arr', sa.FLOAT(), nullable=True))
    op.add_column('deals', sa.Column('startup_name', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('founder_email', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('is_archived', sa.BOOLEAN(), nullable=True))
    op.add_column('deals', sa.Column('ic_readiness', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('churn_rate', sa.FLOAT(), nullable=True))
    op.add_column('deals', sa.Column('revenue_summary', sa.TEXT(), nullable=True))
    op.add_column('deals', sa.Column('ltv', sa.FLOAT(), nullable=True))
    op.add_column('deals', sa.Column('revenue', sa.FLOAT(), nullable=True))
    op.add_column('deals', sa.Column('fundraising_status', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('deals', sa.Column('users', sa.INTEGER(), nullable=True))
    op.add_column('deals', sa.Column('round_size', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('gross_margin', sa.FLOAT(), nullable=True))
    op.add_column('deals', sa.Column('website', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('active_playbook_id', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('tags', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('notes', sa.TEXT(), nullable=True))
    op.add_column('deals', sa.Column('why_interesting', sa.TEXT(), nullable=True))
    op.add_column('deals', sa.Column('founder_background', sa.TEXT(), nullable=True))
    op.add_column('deals', sa.Column('public_profile_json', sa.TEXT(), nullable=True))
    op.add_column('deals', sa.Column('competitors', sa.TEXT(), nullable=True))
    op.add_column('deals', sa.Column('evidence_confidence', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('growth_rate', sa.FLOAT(), nullable=True))
    op.add_column('deals', sa.Column('workspace_id', sa.INTEGER(), nullable=True))
    op.add_column('deals', sa.Column('sector', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('deal_type', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('mrr', sa.FLOAT(), nullable=True))
    op.add_column('deals', sa.Column('founder_name', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('is_public_benchmark', sa.BOOLEAN(), nullable=True))
    op.add_column('deals', sa.Column('is_demo', sa.BOOLEAN(), nullable=True))
    op.add_column('deals', sa.Column('traction_summary', sa.TEXT(), nullable=True))
    op.add_column('deals', sa.Column('business_model', sa.VARCHAR(), nullable=True))
    op.add_column('deals', sa.Column('funding_raised', sa.FLOAT(), nullable=True))
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_deals_company_id'), table_name='deals')
    op.create_index(op.f('ix_deals_workspace_id'), 'deals', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_deals_startup_name'), 'deals', ['startup_name'], unique=False)
    op.create_index(op.f('ix_deals_created_at'), 'deals', ['created_at'], unique=False)
    op.drop_column('deals', 'funding_asking')
    op.drop_column('deals', 'company_id')
    op.add_column('deal_assignments', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_deal_assignments_user_id'), table_name='deal_assignments')
    op.add_column('audit_logs', sa.Column('workspace_id', sa.INTEGER(), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_type', sa.VARCHAR(), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    op.create_table('workspaces',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=1)
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_deal_id'), 'activity_logs', ['deal_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_table('deal_comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('section', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_comments_id'), 'deal_comments', ['id'], unique=False)
    op.create_index(op.f('ix_deal_comments_deal_id'), 'deal_comments', ['deal_id'], unique=False)
    op.create_table('research_briefs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('market_research_json', sa.TEXT(), nullable=True),
    sa.Column('competitor_research_json', sa.TEXT(), nullable=True),
    sa.Column('customer_personas_json', sa.TEXT(), nullable=True),
    sa.Column('pricing_research_json', sa.TEXT(), nullable=True),
    sa.Column('gtm_research_json', sa.TEXT(), nullable=True),
    sa.Column('tam_sam_som_json', sa.TEXT(), nullable=True),
    sa.Column('evidence_grade_json', sa.TEXT(), nullable=True),
    sa.Column('source_registry_json', sa.TEXT(), nullable=True),
    sa.Column('research_gaps_json', sa.TEXT(), nullable=True),
    sa.Column('source_confidence', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_briefs_workspace_id'), 'research_briefs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_research_briefs_id'), 'research_briefs', ['id'], unique=False)
    op.create_index(op.f('ix_research_briefs_deal_id'), 'research_briefs', ['deal_id'], unique=False)
    op.create_table('platform_sources',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('mode', sa.VARCHAR(), nullable=True),
    sa.Column('last_checked_at', sa.DATETIME(), nullable=True),
    sa.Column('setup_note', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_sources_name'), 'platform_sources', ['name'], unique=False)
    op.create_index(op.f('ix_platform_sources_id'), 'platform_sources', ['id'], unique=False)
    op.create_table('ic_packets',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('readiness_label', sa.VARCHAR(), nullable=True),
    sa.Column('markdown_content', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('trust_score', sa.INTEGER(), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ic_packets_id'), 'ic_packets', ['id'], unique=False)
    op.create_index(op.f('ix_ic_packets_deal_id'), 'ic_packets', ['deal_id'], unique=False)
    op.create_table('fund_fit_assessments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('fund_size', sa.INTEGER(), nullable=True),
    sa.Column('initial_check_size', sa.INTEGER(), nullable=True),
    sa.Column('target_ownership', sa.FLOAT(), nullable=True),
    sa.Column('required_exit_value_for_1x_fund', sa.INTEGER(), nullable=True),
    sa.Column('fund_return_potential', sa.VARCHAR(), nullable=True),
    sa.Column('thesis_fit_score', sa.INTEGER(), nullable=True),
    sa.Column('portfolio_concentration_risk', sa.VARCHAR(), nullable=True),
    sa.Column('recommendation', sa.VARCHAR(), nullable=True),
    sa.Column('key_constraints_json', sa.TEXT(), nullable=True),
    sa.Column('thesis_fit_json', sa.TEXT(), nullable=True),
    sa.Column('ownership_scenarios_json', sa.TEXT(), nullable=True),
    sa.Column('reserve_strategy_json', sa.TEXT(), nullable=True),
    sa.Column('power_law_simulation_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_fit_assessments_workspace_id'), 'fund_fit_assessments', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_fund_fit_assessments_recommendation'), 'fund_fit_assessments', ['recommendation'], unique=False)
    op.create_index(op.f('ix_fund_fit_assessments_id'), 'fund_fit_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_fund_fit_assessments_deal_id'), 'fund_fit_assessments', ['deal_id'], unique=False)
    op.create_table('red_flags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('severity', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.INTEGER(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('evidence', sa.TEXT(), nullable=True),
    sa.Column('suggested_diligence', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_red_flags_id'), 'red_flags', ['id'], unique=False)
    op.create_index(op.f('ix_red_flags_deal_id'), 'red_flags', ['deal_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('source_type', sa.VARCHAR(), nullable=True),
    sa.Column('source_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_name', sa.VARCHAR(), nullable=True),
    sa.Column('claim_text', sa.TEXT(), nullable=True),
    sa.Column('claim_category', sa.VARCHAR(), nullable=True),
    sa.Column('verification_status', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.VARCHAR(), nullable=True),
    sa.Column('decision_impact', sa.VARCHAR(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('is_assumption', sa.BOOLEAN(), nullable=True),
    sa.Column('is_unknown', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by_module', sa.VARCHAR(), nullable=True),
    sa.Column('created_by_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_id'), 'evidence_items', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_items_deal_id'), 'evidence_items', ['deal_id'], unique=False)
    op.create_table('operation_tasks',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('source_module', sa.VARCHAR(), nullable=True),
    sa.Column('source_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('owner', sa.VARCHAR(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('blocker_status', sa.VARCHAR(), nullable=True),
    sa.Column('related_document_id', sa.VARCHAR(), nullable=True),
    sa.Column('related_evidence_id', sa.VARCHAR(), nullable=True),
    sa.Column('related_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_tasks_id'), 'operation_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_operation_tasks_deal_id'), 'operation_tasks', ['deal_id'], unique=False)
    op.create_table('decision_outputs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('recommendation', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.VARCHAR(), nullable=True),
    sa.Column('supporting_points_json', sa.TEXT(), nullable=True),
    sa.Column('blockers_json', sa.TEXT(), nullable=True),
    sa.Column('deterministic_gates_json', sa.TEXT(), nullable=True),
    sa.Column('next_actions_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_outputs_id'), 'decision_outputs', ['id'], unique=False)
    op.create_index(op.f('ix_decision_outputs_deal_id'), 'decision_outputs', ['deal_id'], unique=False)
    op.create_table('trust_audits',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('trust_score', sa.INTEGER(), nullable=True),
    sa.Column('trust_level', sa.VARCHAR(), nullable=True),
    sa.Column('grounding_status', sa.VARCHAR(), nullable=True),
    sa.Column('unsupported_claims_count', sa.INTEGER(), nullable=True),
    sa.Column('assumptions_count', sa.INTEGER(), nullable=True),
    sa.Column('unknowns_count', sa.INTEGER(), nullable=True),
    sa.Column('safe_to_share_status', sa.VARCHAR(), nullable=True),
    sa.Column('review_required', sa.BOOLEAN(), nullable=True),
    sa.Column('badges_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_audits_id'), 'trust_audits', ['id'], unique=False)
    op.create_index(op.f('ix_trust_audits_deal_id'), 'trust_audits', ['deal_id'], unique=False)
    op.create_table('assumptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.INTEGER(), nullable=True),
    sa.Column('owner', sa.VARCHAR(), nullable=True),
    sa.Column('supporting_evidence', sa.TEXT(), nullable=True),
    sa.Column('contradicting_evidence', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumptions_id'), 'assumptions', ['id'], unique=False)
    op.create_index(op.f('ix_assumptions_deal_id'), 'assumptions', ['deal_id'], unique=False)
    op.create_table('platform_diligence_runs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('config_json', sa.TEXT(), nullable=True),
    sa.Column('report_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_diligence_runs_id'), 'platform_diligence_runs', ['id'], unique=False)
    op.create_index(op.f('ix_platform_diligence_runs_deal_id'), 'platform_diligence_runs', ['deal_id'], unique=False)
    op.create_table('web_research_briefs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('company_name', sa.VARCHAR(), nullable=True),
    sa.Column('research_mode', sa.VARCHAR(), nullable=True),
    sa.Column('source_quality_score', sa.INTEGER(), nullable=True),
    sa.Column('public_data_confidence', sa.VARCHAR(), nullable=True),
    sa.Column('queries_json', sa.TEXT(), nullable=True),
    sa.Column('sources_json', sa.TEXT(), nullable=True),
    sa.Column('claims_json', sa.TEXT(), nullable=True),
    sa.Column('evidence_graph_json', sa.TEXT(), nullable=True),
    sa.Column('conflicts_json', sa.TEXT(), nullable=True),
    sa.Column('unknown_metrics_json', sa.TEXT(), nullable=True),
    sa.Column('synthesis_json', sa.TEXT(), nullable=True),
    sa.Column('citations_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_research_briefs_workspace_id'), 'web_research_briefs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_web_research_briefs_id'), 'web_research_briefs', ['id'], unique=False)
    op.create_index(op.f('ix_web_research_briefs_deal_id'), 'web_research_briefs', ['deal_id'], unique=False)
    op.create_table('diligence_run_steps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(), nullable=True),
    sa.Column('step_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('summary', sa.VARCHAR(), nullable=True),
    sa.Column('outputs_json', sa.VARCHAR(), nullable=True),
    sa.Column('warnings_json', sa.VARCHAR(), nullable=True),
    sa.Column('errors_json', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diligence_run_steps_run_id'), 'diligence_run_steps', ['run_id'], unique=False)
    op.create_index(op.f('ix_diligence_run_steps_id'), 'diligence_run_steps', ['id'], unique=False)
    op.create_table('diligence_runs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('company_name', sa.VARCHAR(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('mode', sa.VARCHAR(), nullable=True),
    sa.Column('final_recommendation', sa.VARCHAR(), nullable=True),
    sa.Column('evidence_confidence', sa.VARCHAR(), nullable=True),
    sa.Column('trust_score', sa.INTEGER(), nullable=True),
    sa.Column('ic_readiness', sa.VARCHAR(), nullable=True),
    sa.Column('missing_information_json', sa.VARCHAR(), nullable=True),
    sa.Column('critical_blockers_json', sa.VARCHAR(), nullable=True),
    sa.Column('next_actions_json', sa.VARCHAR(), nullable=True),
    sa.Column('report_json', sa.VARCHAR(), nullable=True),
    sa.Column('metadata_json', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diligence_runs_id'), 'diligence_runs', ['id'], unique=False)
    op.create_index(op.f('ix_diligence_runs_deal_id'), 'diligence_runs', ['deal_id'], unique=False)
    op.create_table('deal_data_room_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.VARCHAR(), nullable=True),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('file_name', sa.VARCHAR(), nullable=True),
    sa.Column('file_type', sa.VARCHAR(), nullable=True),
    sa.Column('document_category', sa.VARCHAR(), nullable=True),
    sa.Column('upload_time', sa.DATETIME(), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('storage_path', sa.VARCHAR(), nullable=True),
    sa.Column('parse_status', sa.VARCHAR(), nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), nullable=True),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_data_room_documents_id'), 'deal_data_room_documents', ['id'], unique=False)
    op.create_index(op.f('ix_deal_data_room_documents_document_id'), 'deal_data_room_documents', ['document_id'], unique=1)
    op.create_table('agent_traces',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(), nullable=True),
    sa.Column('agent_name', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('output', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_run_id'), 'agent_traces', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_id'), 'agent_traces', ['id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.Column('original_filename', sa.VARCHAR(), nullable=True),
    sa.Column('content_type', sa.VARCHAR(), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=True),
    sa.Column('storage_provider', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_workspace_id'), 'uploaded_files', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_deal_id'), 'uploaded_files', ['deal_id'], unique=False)
    op.create_table('deck_analyses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('deck_name', sa.VARCHAR(), nullable=True),
    sa.Column('file_type', sa.VARCHAR(), nullable=True),
    sa.Column('raw_text', sa.TEXT(), nullable=True),
    sa.Column('extracted_sections_json', sa.TEXT(), nullable=True),
    sa.Column('key_claims_json', sa.TEXT(), nullable=True),
    sa.Column('traction_json', sa.TEXT(), nullable=True),
    sa.Column('financials_json', sa.TEXT(), nullable=True),
    sa.Column('risks_json', sa.TEXT(), nullable=True),
    sa.Column('missing_sections_json', sa.TEXT(), nullable=True),
    sa.Column('deck_quality_json', sa.TEXT(), nullable=True),
    sa.Column('readiness_breakdown_json', sa.TEXT(), nullable=True),
    sa.Column('recommended_follow_up_questions_json', sa.TEXT(), nullable=True),
    sa.Column('deck_summary', sa.TEXT(), nullable=True),
    sa.Column('deck_quality_score', sa.INTEGER(), nullable=True),
    sa.Column('investor_readiness_score', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_analyses_workspace_id'), 'deck_analyses', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_deck_analyses_id'), 'deck_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_deck_analyses_deal_id'), 'deck_analyses', ['deal_id'], unique=False)
    op.create_table('deal_war_rooms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('company_name', sa.VARCHAR(), nullable=True),
    sa.Column('war_room_status', sa.VARCHAR(), nullable=True),
    sa.Column('thesis_json', sa.TEXT(), nullable=True),
    sa.Column('anti_thesis_json', sa.TEXT(), nullable=True),
    sa.Column('what_must_be_true_json', sa.TEXT(), nullable=True),
    sa.Column('partner_personas_json', sa.TEXT(), nullable=True),
    sa.Column('partner_questions_json', sa.TEXT(), nullable=True),
    sa.Column('ic_simulation_json', sa.TEXT(), nullable=True),
    sa.Column('conviction_score_json', sa.TEXT(), nullable=True),
    sa.Column('conviction_deltas_json', sa.TEXT(), nullable=True),
    sa.Column('valuation_sensitivity_json', sa.TEXT(), nullable=True),
    sa.Column('ownership_scenarios_json', sa.TEXT(), nullable=True),
    sa.Column('fund_return_scenarios_json', sa.TEXT(), nullable=True),
    sa.Column('change_our_mind_json', sa.TEXT(), nullable=True),
    sa.Column('decision_gates_json', sa.TEXT(), nullable=True),
    sa.Column('final_recommendation_json', sa.TEXT(), nullable=True),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_war_rooms_workspace_id'), 'deal_war_rooms', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_deal_war_rooms_id'), 'deal_war_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_deal_war_rooms_deal_id'), 'deal_war_rooms', ['deal_id'], unique=False)
    op.create_table('platform_signals',
    sa.Column('signal_id', sa.VARCHAR(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(), nullable=True),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('company_name', sa.VARCHAR(), nullable=True),
    sa.Column('platform', sa.VARCHAR(), nullable=True),
    sa.Column('source_url', sa.VARCHAR(), nullable=True),
    sa.Column('source_title', sa.VARCHAR(), nullable=True),
    sa.Column('published_at', sa.VARCHAR(), nullable=True),
    sa.Column('snippet', sa.TEXT(), nullable=True),
    sa.Column('signal_type', sa.VARCHAR(), nullable=True),
    sa.Column('sentiment', sa.VARCHAR(), nullable=True),
    sa.Column('relevance_score', sa.INTEGER(), nullable=True),
    sa.Column('confidence', sa.VARCHAR(), nullable=True),
    sa.Column('verification_status', sa.VARCHAR(), nullable=True),
    sa.Column('decision_impact', sa.VARCHAR(), nullable=True),
    sa.Column('bias_warning', sa.VARCHAR(), nullable=True),
    sa.Column('next_action', sa.VARCHAR(), nullable=True),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_platform_signals_signal_id'), 'platform_signals', ['signal_id'], unique=False)
    op.create_index(op.f('ix_platform_signals_run_id'), 'platform_signals', ['run_id'], unique=False)
    op.create_index(op.f('ix_platform_signals_platform'), 'platform_signals', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_signals_deal_id'), 'platform_signals', ['deal_id'], unique=False)
    op.create_table('deal_documents',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('file_name', sa.VARCHAR(), nullable=True),
    sa.Column('original_file_name', sa.VARCHAR(), nullable=True),
    sa.Column('file_type', sa.VARCHAR(), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('document_type', sa.VARCHAR(), nullable=True),
    sa.Column('processing_status', sa.VARCHAR(), nullable=True),
    sa.Column('storage_path', sa.VARCHAR(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('parser_confidence', sa.VARCHAR(), nullable=True),
    sa.Column('trust_status', sa.VARCHAR(), nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), nullable=True),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_documents_id'), 'deal_documents', ['id'], unique=False)
    op.create_table('web_sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('research_id', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('domain', sa.VARCHAR(), nullable=True),
    sa.Column('source_type', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.VARCHAR(), nullable=True),
    sa.Column('fetched_at', sa.VARCHAR(), nullable=True),
    sa.Column('content_hash', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['research_id'], ['web_research_briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_sources_research_id'), 'web_sources', ['research_id'], unique=False)
    op.create_index(op.f('ix_web_sources_id'), 'web_sources', ['id'], unique=False)
    op.create_table('diligence_plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('ic_readiness_score', sa.INTEGER(), nullable=True),
    sa.Column('diligence_status', sa.VARCHAR(), nullable=True),
    sa.Column('final_diligence_verdict', sa.VARCHAR(), nullable=True),
    sa.Column('priority_tasks_json', sa.TEXT(), nullable=True),
    sa.Column('claim_verifications_json', sa.TEXT(), nullable=True),
    sa.Column('founder_followups_json', sa.TEXT(), nullable=True),
    sa.Column('customer_reference_questions_json', sa.TEXT(), nullable=True),
    sa.Column('data_room_requests_json', sa.TEXT(), nullable=True),
    sa.Column('risk_resolution_plan_json', sa.TEXT(), nullable=True),
    sa.Column('evidence_items_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diligence_plans_workspace_id'), 'diligence_plans', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_diligence_plans_id'), 'diligence_plans', ['id'], unique=False)
    op.create_index(op.f('ix_diligence_plans_deal_id'), 'diligence_plans', ['deal_id'], unique=False)
    op.create_table('decision_audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('previous_recommendation', sa.VARCHAR(), nullable=True),
    sa.Column('current_recommendation', sa.VARCHAR(), nullable=True),
    sa.Column('reason_changed', sa.TEXT(), nullable=True),
    sa.Column('evidence_responsible', sa.TEXT(), nullable=True),
    sa.Column('confidence_change', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('previous_health_score', sa.INTEGER(), nullable=True),
    sa.Column('current_health_score', sa.INTEGER(), nullable=True),
    sa.Column('health_score_change', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_audit_logs_id'), 'decision_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_decision_audit_logs_deal_id'), 'decision_audit_logs', ['deal_id'], unique=False)
    op.create_table('agent_workflow_runs',
    sa.Column('run_id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.VARCHAR(), nullable=True),
    sa.Column('company_name', sa.VARCHAR(), nullable=True),
    sa.Column('workflow_mode', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('agents_run', sa.VARCHAR(), nullable=True),
    sa.Column('trace', sa.VARCHAR(), nullable=True),
    sa.Column('final_report', sa.VARCHAR(), nullable=True),
    sa.Column('metadata_blob', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_agent_workflow_runs_run_id'), 'agent_workflow_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_workflow_runs_deal_id'), 'agent_workflow_runs', ['deal_id'], unique=False)
    op.create_table('deal_data_room_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('report_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id')
    )
    op.create_index(op.f('ix_deal_data_room_reports_id'), 'deal_data_room_reports', ['id'], unique=False)
    op.create_table('demo_seed_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seeded_at', sa.DATETIME(), nullable=True),
    sa.Column('is_seeded', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_seed_status_id'), 'demo_seed_status', ['id'], unique=False)
    op.create_table('investment_theses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('bull_case', sa.TEXT(), nullable=True),
    sa.Column('bear_case', sa.TEXT(), nullable=True),
    sa.Column('recommendation', sa.VARCHAR(), nullable=True),
    sa.Column('conviction', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.INTEGER(), nullable=True),
    sa.Column('unknowns', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('health_score', sa.INTEGER(), server_default=sa.text('(50)'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_theses_id'), 'investment_theses', ['id'], unique=False)
    op.create_index(op.f('ix_investment_theses_deal_id'), 'investment_theses', ['deal_id'], unique=1)
    op.create_table('workspace_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_id'), 'workspace_members', ['id'], unique=False)
    op.create_table('conversation_rounds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('round_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('conversation_type', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('participants_json', sqlite.JSON(), nullable=True),
    sa.Column('raw_text', sa.TEXT(), nullable=True),
    sa.Column('parsed_messages_json', sqlite.JSON(), nullable=True),
    sa.Column('round_score', sa.INTEGER(), nullable=True),
    sa.Column('key_signal', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_rounds_workspace_id'), 'conversation_rounds', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_conversation_rounds_id'), 'conversation_rounds', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_rounds_deal_id'), 'conversation_rounds', ['deal_id'], unique=False)
    op.create_index(op.f('ix_conversation_rounds_created_at'), 'conversation_rounds', ['created_at'], unique=False)
    op.create_table('ic_decision_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('decision_date', sa.DATETIME(), nullable=True),
    sa.Column('decision', sa.VARCHAR(), nullable=True),
    sa.Column('decision_rationale', sa.TEXT(), nullable=True),
    sa.Column('conditions', sa.TEXT(), nullable=True),
    sa.Column('partner_concerns', sa.TEXT(), nullable=True),
    sa.Column('next_step', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ic_decision_logs_workspace_id'), 'ic_decision_logs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_ic_decision_logs_id'), 'ic_decision_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ic_decision_logs_decision'), 'ic_decision_logs', ['decision'], unique=False)
    op.create_index(op.f('ix_ic_decision_logs_deal_id'), 'ic_decision_logs', ['deal_id'], unique=False)
    op.create_table('conversation_intelligence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('founder_response_quality_score', sa.INTEGER(), nullable=True),
    sa.Column('clarity_score', sa.INTEGER(), nullable=True),
    sa.Column('responsiveness_score', sa.INTEGER(), nullable=True),
    sa.Column('credibility_score', sa.INTEGER(), nullable=True),
    sa.Column('evidence_provided_score', sa.INTEGER(), nullable=True),
    sa.Column('contradiction_risk_score', sa.INTEGER(), nullable=True),
    sa.Column('overall_conversation_score', sa.INTEGER(), nullable=True),
    sa.Column('scorecard_json', sqlite.JSON(), nullable=True),
    sa.Column('founder_analysis_json', sqlite.JSON(), nullable=True),
    sa.Column('investor_questions_json', sqlite.JSON(), nullable=True),
    sa.Column('positive_signals_json', sqlite.JSON(), nullable=True),
    sa.Column('negative_signals_json', sqlite.JSON(), nullable=True),
    sa.Column('contradictions_json', sqlite.JSON(), nullable=True),
    sa.Column('evidence_extracted_json', sqlite.JSON(), nullable=True),
    sa.Column('open_followups_json', sqlite.JSON(), nullable=True),
    sa.Column('decision_impact_json', sqlite.JSON(), nullable=True),
    sa.Column('recommendation_adjustment', sa.VARCHAR(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_intelligence_workspace_id'), 'conversation_intelligence', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_conversation_intelligence_id'), 'conversation_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_intelligence_deal_id'), 'conversation_intelligence', ['deal_id'], unique=1)
    op.create_index(op.f('ix_conversation_intelligence_created_at'), 'conversation_intelligence', ['created_at'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=True),
    sa.Column('full_analysis_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_workspace_id'), 'analyses', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_analyses_deal_id'), 'analyses', ['deal_id'], unique=False)
    op.create_table('missing_info_items',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.INTEGER(), nullable=True),
    sa.Column('field_name', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('severity', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('why_it_matters', sa.TEXT(), nullable=True),
    sa.Column('source_module', sa.VARCHAR(), nullable=True),
    sa.Column('resolved_by_document_id', sa.VARCHAR(), nullable=True),
    sa.Column('resolved_by_evidence_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missing_info_items_id'), 'missing_info_items', ['id'], unique=False)
    op.create_index(op.f('ix_missing_info_items_deal_id'), 'missing_info_items', ['deal_id'], unique=False)
    # ### end Alembic commands ###
