"""phase 2a-s security and idempotency

Revision ID: 7adc77359479
Revises: ea64aa6f63ad
Create Date: 2026-07-09 13:33:04.232800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7adc77359479'
down_revision: Union[str, Sequence[str], None] = 'ea64aa6f63ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_memberships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_memberships_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('challenge_tasks', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_decision_fingerprint', ['decision_id', 'trigger_fingerprint'])

    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_decisions_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key('fk_decisions_workspace_id', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reasoning_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reasoning_runs_run_key'), ['run_key'], unique=True)
        
    # --- DATA MIGRATION: Safe Workspace Backfill ---
    connection = op.get_bind()
    import os
    
    # Safety Check A: Explicitly verify this is pre-multi-user staging
    user_count = connection.execute(sa.text("SELECT count(id) FROM users")).scalar()
    app_env = os.environ.get("APP_ENV", "local")
    if user_count > 5 and app_env != "local":
        raise Exception("MIGRATION SAFETY ABORT: Multi-user data exists in non-local environment. Cannot safely auto-backfill into a single workspace.")
    
    # 1. Ensure Default Workspace exists
    workspace_id = connection.execute(sa.text("SELECT id FROM workspaces WHERE name='Default Workspace'")).scalar()
    if not workspace_id:
        connection.execute(sa.text("INSERT INTO workspaces (name) VALUES ('Default Workspace')"))
        workspace_id = connection.execute(sa.text("SELECT id FROM workspaces WHERE name='Default Workspace'")).scalar()
        
    # 2. Add all existing users to Default Workspace
    user_ids = connection.execute(sa.text("SELECT id FROM users")).fetchall()
    for row in user_ids:
        uid = row[0]
        exists = connection.execute(sa.text(f"SELECT id FROM workspace_memberships WHERE user_id={uid} AND workspace_id={workspace_id}")).scalar()
        if not exists:
            connection.execute(sa.text(f"INSERT INTO workspace_memberships (workspace_id, user_id, role) VALUES ({workspace_id}, {uid}, 'Admin')"))
            
    # 3. Backfill Decisions
    connection.execute(sa.text(f"UPDATE decisions SET workspace_id = {workspace_id} WHERE workspace_id IS NULL"))
    
    # 4. Enforce NOT NULL on workspace_id (Note: sqlite batch_alter_table handles this)
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.alter_column('workspace_id', existing_type=sa.Integer(), nullable=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reasoning_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reasoning_runs_run_key'))
        batch_op.drop_column('run_key')

    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_decisions_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('challenge_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_decision_fingerprint', type_='unique')

    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_memberships_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_memberships_id'))

    op.drop_table('workspace_memberships')
    # ### end Alembic commands ###
