"""phase_2_integrity_hardening

Revision ID: a8190894c749
Revises: 7397de62b953
Create Date: 2026-07-04 12:58:32.375514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8190894c749'
down_revision: Union[str, Sequence[str], None] = '7397de62b953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envelope_critical_assumptions',
    sa.Column('envelope_id', sa.Integer(), nullable=False),
    sa.Column('assumption_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['assumptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['envelope_id'], ['decision_integrity_envelopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('envelope_id', 'assumption_id')
    )
    op.create_table('envelope_hard_conflicts',
    sa.Column('envelope_id', sa.Integer(), nullable=False),
    sa.Column('conflict_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['evidence_conflicts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['envelope_id'], ['decision_integrity_envelopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('envelope_id', 'conflict_id')
    )
    op.create_table('envelope_unresolved_signals',
    sa.Column('envelope_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['decision_integrity_envelopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['escalation_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('envelope_id', 'signal_id')
    )
    with op.batch_alter_table('challenge_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escalation_signal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_challenge_tasks_escalation_signal_id', 'escalation_signals', ['escalation_signal_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('escalation_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_conflict_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assumption_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_escalation_signals_evidence_conflict_id', 'evidence_conflicts', ['evidence_conflict_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_escalation_signals_assumption_id', 'assumptions', ['assumption_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('human_decision_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_human_decision_records_recommendation_id', 'recommendations', ['recommendation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_decision_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_human_decision_records_recommendation_id', type_='foreignkey')
        batch_op.drop_column('recommendation_id')

    with op.batch_alter_table('escalation_signals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_escalation_signals_assumption_id', type_='foreignkey')
        batch_op.drop_constraint('fk_escalation_signals_evidence_conflict_id', type_='foreignkey')
        batch_op.drop_column('assumption_id')
        batch_op.drop_column('evidence_conflict_id')

    with op.batch_alter_table('challenge_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_challenge_tasks_escalation_signal_id', type_='foreignkey')
        batch_op.drop_column('escalation_signal_id')

    op.drop_table('envelope_unresolved_signals')
    op.drop_table('envelope_hard_conflicts')
    op.drop_table('envelope_critical_assumptions')
    # ### end Alembic commands ###
