"""Execution Ticket ActionItems

Revision ID: adec3a9c4f68
Revises: 63de8db1c619
Create Date: 2026-07-13 13:47:13.183598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adec3a9c4f68'
down_revision: Union[str, Sequence[str], None] = '63de8db1c619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('why_investors_care', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('missing_evidence', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('definition_of_done', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estimated_effort', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('expected_impact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('verification_criteria', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_column('verification_criteria')
        batch_op.drop_column('expected_impact')
        batch_op.drop_column('estimated_effort')
        batch_op.drop_column('definition_of_done')
        batch_op.drop_column('missing_evidence')
        batch_op.drop_column('why_investors_care')
        batch_op.drop_column('problem')

    # ### end Alembic commands ###
