"""Add Recommendation versioning

Revision ID: b4b2d545a4e0
Revises: adec3a9c4f68
Create Date: 2026-07-16 15:27:28.868727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b2d545a4e0'
down_revision: Union[str, Sequence[str], None] = 'adec3a9c4f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reasons_confidence_increased_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reasons_confidence_decreased_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('triggering_event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_recommendations_event_id', 'domain_events', ['triggering_event_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recommendations_event_id', type_='foreignkey')
        batch_op.drop_column('triggering_event_id')
        batch_op.drop_column('reasons_confidence_decreased_json')
        batch_op.drop_column('reasons_confidence_increased_json')
        batch_op.drop_column('version')

    # ### end Alembic commands ###
