"""Init V4 Schema Base

Revision ID: d806a11fb8be
Revises: 
Create Date: 2026-07-03 19:41:56.037389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd806a11fb8be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_subjects_id'), 'decision_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_decision_subjects_name'), 'decision_subjects', ['name'], unique=False)
    op.create_table('domain_packs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_packs_id'), 'domain_packs', ['id'], unique=False)
    op.create_index(op.f('ix_domain_packs_name'), 'domain_packs', ['name'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_pack_id', sa.String(), nullable=True),
    sa.Column('pattern_type', sa.String(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('supporting_decisions_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_sources_id'), 'platform_sources', ['id'], unique=False)
    op.create_index(op.f('ix_platform_sources_name'), 'platform_sources', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_table('decision_frameworks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('domain_pack_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('stages_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_pack_id'], ['domain_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_frameworks_domain_pack_id'), 'decision_frameworks', ['domain_pack_id'], unique=False)
    op.create_index(op.f('ix_decision_frameworks_id'), 'decision_frameworks', ['id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('domain_pack_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('base_analysis_calls', sa.Integer(), nullable=True),
    sa.Column('challenge_calls', sa.Integer(), nullable=True),
    sa.Column('synthesis_calls', sa.Integer(), nullable=True),
    sa.Column('grader_calls', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('escalation_reason', sa.String(), nullable=True),
    sa.Column('avoided_full_deliberation_estimate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_pack_id'], ['domain_packs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['decision_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_index(op.f('ix_decisions_status'), 'decisions', ['status'], unique=False)
    op.create_index(op.f('ix_decisions_subject_id'), 'decisions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_decisions_title'), 'decisions', ['title'], unique=False)
    op.create_table('reasoning_agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('domain_pack_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('capabilities_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_pack_id'], ['domain_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reasoning_agents_domain_pack_id'), 'reasoning_agents', ['domain_pack_id'], unique=False)
    op.create_index(op.f('ix_reasoning_agents_id'), 'reasoning_agents', ['id'], unique=False)
    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('milestones_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_plans_decision_id'), 'action_plans', ['decision_id'], unique=False)
    op.create_index(op.f('ix_action_plans_id'), 'action_plans', ['id'], unique=False)
    op.create_table('assumptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumptions_category'), 'assumptions', ['category'], unique=False)
    op.create_index(op.f('ix_assumptions_decision_id'), 'assumptions', ['decision_id'], unique=False)
    op.create_table('decision_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_assignments_decision_id'), 'decision_assignments', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_assignments_id'), 'decision_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_decision_assignments_user_id'), 'decision_assignments', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_decision_id'), 'documents', ['decision_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_decision_id'), 'evidence', ['decision_id'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_nodes_id'), 'graph_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_graph_nodes_node_type'), 'graph_nodes', ['node_type'], unique=False)
    op.create_table('human_decision_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('ai_recommendation', sa.String(), nullable=True),
    sa.Column('ai_confidence', sa.Integer(), nullable=True),
    sa.Column('escalation_signals_json', sa.Text(), nullable=True),
    sa.Column('challenges_performed_json', sa.Text(), nullable=True),
    sa.Column('material_position_changes_json', sa.Text(), nullable=True),
    sa.Column('unresolved_conflicts_json', sa.Text(), nullable=True),
    sa.Column('human_final_decision', sa.String(), nullable=True),
    sa.Column('human_rationale', sa.Text(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('approvers_json', sa.Text(), nullable=True),
    sa.Column('conditions_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_table('institutional_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('predicted_outcome', sa.Text(), nullable=True),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('lessons_learned_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_memory_decision_id'), 'institutional_memory', ['decision_id'], unique=False)
    op.create_index(op.f('ix_institutional_memory_id'), 'institutional_memory', ['id'], unique=False)
    op.create_table('platform_diligence_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_diligence_runs_decision_id'), 'platform_diligence_runs', ['decision_id'], unique=False)
    op.create_index(op.f('ix_platform_diligence_runs_id'), 'platform_diligence_runs', ['id'], unique=False)
    op.create_table('platform_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_signals_decision_id'), 'platform_signals', ['decision_id'], unique=False)
    op.create_table('postmortems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('decision_quality_score', sa.Integer(), nullable=True),
    sa.Column('outcome_quality_score', sa.Integer(), nullable=True),
    sa.Column('went_right', sa.Text(), nullable=True),
    sa.Column('went_wrong', sa.Text(), nullable=True),
    sa.Column('lessons_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('target_metric', sa.String(), nullable=True),
    sa.Column('expected_value', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('expected_date', sa.DateTime(), nullable=True),
    sa.Column('actual_result', sa.String(), nullable=True),
    sa.Column('error_magnitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_decision_id'), 'predictions', ['decision_id'], unique=False)
    op.create_table('reasoning_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_run_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('domain_pack_id', sa.String(), nullable=True),
    sa.Column('execution_mode', sa.String(), nullable=True),
    sa.Column('evaluation_path', sa.String(), nullable=True),
    sa.Column('execution_topology', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stage_status', sa.String(), nullable=True),
    sa.Column('accumulated_cost', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('reasoning_config_json', sa.Text(), nullable=True),
    sa.Column('memory_enabled', sa.Boolean(), nullable=True),
    sa.Column('agent_config_json', sa.Text(), nullable=True),
    sa.Column('retrieval_config_json', sa.Text(), nullable=True),
    sa.Column('git_commit_hash', sa.String(), nullable=True),
    sa.Column('latency_ms_json', sa.Text(), nullable=True),
    sa.Column('cost_json', sa.Text(), nullable=True),
    sa.Column('token_usage_json', sa.Text(), nullable=True),
    sa.Column('memory_objects_used_json', sa.Text(), nullable=True),
    sa.Column('claims_used_json', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('errors_json', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reasoning_runs_decision_id'), 'reasoning_runs', ['decision_id'], unique=False)
    op.create_index(op.f('ix_reasoning_runs_evaluation_run_id'), 'reasoning_runs', ['evaluation_run_id'], unique=False)
    op.create_table('scenario_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('scenario_type', sa.String(), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('forecast_results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_simulations_decision_id'), 'scenario_simulations', ['decision_id'], unique=False)
    op.create_index(op.f('ix_scenario_simulations_id'), 'scenario_simulations', ['id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('canonical_content', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_id'), 'chunks', ['id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_node_id', sa.String(), nullable=True),
    sa.Column('target_node_id', sa.String(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_relationship'), 'graph_edges', ['relationship'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_node_id'), 'graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_node_id'), 'graph_edges', ['target_node_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('reasoning_run_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_value', sa.String(), nullable=True),
    sa.Column('recommendation_type', sa.String(), nullable=True),
    sa.Column('model_confidence', sa.Integer(), nullable=True),
    sa.Column('key_risks_json', sa.Text(), nullable=True),
    sa.Column('missing_information_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reasoning_run_id'], ['reasoning_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_decision_id'), 'recommendations', ['decision_id'], unique=False)
    op.create_index(op.f('ix_recommendations_reasoning_run_id'), 'recommendations', ['reasoning_run_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('provenance_type', sa.String(), nullable=True),
    sa.Column('source_chunk_id', sa.Integer(), nullable=True),
    sa.Column('quoted_evidence_span', sa.Text(), nullable=True),
    sa.Column('character_offsets_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('extraction_rationale', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('related_assertions_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_decision_id'), 'claims', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_decision_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_recommendations_reasoning_run_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_decision_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_graph_edges_target_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_relationship'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_chunks_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_scenario_simulations_id'), table_name='scenario_simulations')
    op.drop_index(op.f('ix_scenario_simulations_decision_id'), table_name='scenario_simulations')
    op.drop_table('scenario_simulations')
    op.drop_index(op.f('ix_reasoning_runs_evaluation_run_id'), table_name='reasoning_runs')
    op.drop_index(op.f('ix_reasoning_runs_decision_id'), table_name='reasoning_runs')
    op.drop_table('reasoning_runs')
    op.drop_index(op.f('ix_predictions_decision_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('postmortems')
    op.drop_index(op.f('ix_platform_signals_decision_id'), table_name='platform_signals')
    op.drop_table('platform_signals')
    op.drop_index(op.f('ix_platform_diligence_runs_id'), table_name='platform_diligence_runs')
    op.drop_index(op.f('ix_platform_diligence_runs_decision_id'), table_name='platform_diligence_runs')
    op.drop_table('platform_diligence_runs')
    op.drop_index(op.f('ix_institutional_memory_id'), table_name='institutional_memory')
    op.drop_index(op.f('ix_institutional_memory_decision_id'), table_name='institutional_memory')
    op.drop_table('institutional_memory')
    op.drop_table('human_decision_records')
    op.drop_index(op.f('ix_graph_nodes_node_type'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_id'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_decision_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_decision_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_decision_assignments_user_id'), table_name='decision_assignments')
    op.drop_index(op.f('ix_decision_assignments_id'), table_name='decision_assignments')
    op.drop_index(op.f('ix_decision_assignments_decision_id'), table_name='decision_assignments')
    op.drop_table('decision_assignments')
    op.drop_index(op.f('ix_assumptions_decision_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_category'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_action_plans_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_decision_id'), table_name='action_plans')
    op.drop_table('action_plans')
    op.drop_index(op.f('ix_reasoning_agents_id'), table_name='reasoning_agents')
    op.drop_index(op.f('ix_reasoning_agents_domain_pack_id'), table_name='reasoning_agents')
    op.drop_table('reasoning_agents')
    op.drop_index(op.f('ix_decisions_title'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_subject_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_status'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_decision_frameworks_id'), table_name='decision_frameworks')
    op.drop_index(op.f('ix_decision_frameworks_domain_pack_id'), table_name='decision_frameworks')
    op.drop_table('decision_frameworks')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_platform_sources_name'), table_name='platform_sources')
    op.drop_index(op.f('ix_platform_sources_id'), table_name='platform_sources')
    op.drop_table('platform_sources')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_domain_packs_name'), table_name='domain_packs')
    op.drop_index(op.f('ix_domain_packs_id'), table_name='domain_packs')
    op.drop_table('domain_packs')
    op.drop_index(op.f('ix_decision_subjects_name'), table_name='decision_subjects')
    op.drop_index(op.f('ix_decision_subjects_id'), table_name='decision_subjects')
    op.drop_table('decision_subjects')
    # ### end Alembic commands ###
