"""Add unique constraint to challenge finding

Revision ID: e3f438b2c7ca
Revises: 7adc77359479
Create Date: 2026-07-10 08:30:02.204703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f438b2c7ca'
down_revision: Union[str, Sequence[str], None] = '7adc77359479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_findings_challenge_task_id'))
        batch_op.create_index(batch_op.f('ix_challenge_findings_challenge_task_id'), ['challenge_task_id'], unique=True)

    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.alter_column('workspace_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.alter_column('workspace_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('challenge_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_findings_challenge_task_id'))
        batch_op.create_index(batch_op.f('ix_challenge_findings_challenge_task_id'), ['challenge_task_id'], unique=False)

    # ### end Alembic commands ###
