"""Phase 1C-B State Loop

Revision ID: ea64aa6f63ad
Revises: a8190894c749
Create Date: 2026-07-09 11:57:46.278973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea64aa6f63ad'
down_revision: Union[str, Sequence[str], None] = 'a8190894c749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assumption_claim_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assumption_id', sa.Integer(), nullable=True),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('provenance_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assumption_id'], ['assumptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assumption_claim_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assumption_claim_links_assumption_id'), ['assumption_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assumption_claim_links_claim_id'), ['claim_id'], unique=False)

    with op.batch_alter_table('challenge_findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolution_effect', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('assumption_effect', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strength', sa.String(), nullable=True))

    with op.batch_alter_table('challenge_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger_fingerprint', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_challenge_tasks_trigger_fingerprint'), ['trigger_fingerprint'], unique=False)

    with op.batch_alter_table('evidence_conflicts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('origin', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_conflicts', schema=None) as batch_op:
        batch_op.drop_column('origin')
        batch_op.drop_column('status')

    with op.batch_alter_table('challenge_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_tasks_trigger_fingerprint'))
        batch_op.drop_column('trigger_fingerprint')

    with op.batch_alter_table('challenge_findings', schema=None) as batch_op:
        batch_op.drop_column('strength')
        batch_op.drop_column('assumption_effect')
        batch_op.drop_column('resolution_effect')

    with op.batch_alter_table('assumption_claim_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assumption_claim_links_claim_id'))
        batch_op.drop_index(batch_op.f('ix_assumption_claim_links_assumption_id'))

    op.drop_table('assumption_claim_links')
    # ### end Alembic commands ###
